# Generated by Django 5.1.2 on 2024-10-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=120, verbose_name='Artist')),
                ('date', models.DateField(verbose_name='Date')),
                ('venue', models.CharField(max_length=120, verbose_name='Venue')),
                ('time', models.TimeField(verbose_name='Time')),
                ('link', models.URLField(verbose_name='EventInfo')),
            ],
        ),
    ]
