# Generated by Django 5.1.2 on 2024-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0002_event_ages_event_exclude_event_price_event_sold_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ticket Price'),
        ),
    ]
