# Generated by Django 5.1.2 on 2024-10-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0003_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(max_length=500, verbose_name='EventInfo'),
        ),
    ]
