# Generated by Django 5.1.2 on 2024-10-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0007_alter_event_ages_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.CharField(max_length=500, verbose_name='Artist'),
        ),
    ]
