# Generated by Django 5.1.2 on 2024-11-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0008_alter_event_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ticket Price'),
        ),
    ]
