# Generated by Django 5.1.2 on 2024-11-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0009_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='exclude',
            field=models.BooleanField(blank=True, null=True, verbose_name='ExcludeFromWeekly'),
        ),
    ]
