# Generated by Django 5.1.2 on 2024-11-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0010_alter_event_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='exclude',
            field=models.BooleanField(blank=True, null=True, verbose_name='Exclude From Weekly'),
        ),
    ]
